"use client";

import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from "recharts";
import { Download } from "lucide-react";
import { PageFrame } from "@/components/page-frame";
import { TerminalTooltip } from "@/components/charts";
import { useApi } from "@/hooks/use-api";
import type { OracleRound } from "@/lib/types";
import { Button, DataUnavailable, Metric, Panel, PanelHeader, ProvenanceBadge, SourceFooter, StatusBadge } from "@/components/ui/primitives";
import { cn, downloadData, toCsv } from "@/lib/utils";

interface OracleResponse { data: OracleRound[]; provenance: { source: string; type: string; calculation: string } }
const tabs = ["PRICE", "DEVIATION", "FRESHNESS", "ANOMALIES", "RAW ROUNDS"];

export function OraclePage() {
  const result = useApi<OracleResponse>("/api/oracle");
  const [tab, setTab] = useState("PRICE");
  const rounds = result.data?.data ?? [];
  const anomalies = rounds.filter((round) => round.status !== "normal");
  const average = rounds.length ? rounds.reduce((sum, round) => sum + round.price, 0) / rounds.length : null;
  const maxZ = rounds.reduce((max, round) => Math.max(max, Math.abs(round.zScore ?? 0)), 0);
  const latest = rounds.at(-1);
  const exportRows = () => downloadData("safe-sphere-chainlink-analysis.csv", toCsv(rounds as unknown as Record<string, unknown>[]), "text/csv");
  const chartData = rounds.map((round) => ({ ...round, label: round.dateTime.slice(5, 16), absZ: Math.abs(round.zScore ?? 0), intervalHours: round.interval ? round.interval / 3600 : null }));

  let view = <Panel><PanelHeader title="Price history" meta="TUSD / USD" action={<ProvenanceBadge type="HISTORICAL" />} /><div className="h-[390px] p-3">{rounds.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="oracle-price" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#b6ff4a" stopOpacity=".16" /><stop offset="1" stopColor="#b6ff4a" stopOpacity="0" /></linearGradient></defs><CartesianGrid stroke="#202420" vertical={false} /><XAxis dataKey="label" stroke="#555b55" fontSize={8} tickLine={false} axisLine={false} minTickGap={45} /><YAxis domain={[.985, 1.015]} stroke="#555b55" fontSize={8} tickLine={false} axisLine={false} width={45} /><Tooltip content={<TerminalTooltip />} /><ReferenceLine y={1} stroke="#555b55" strokeDasharray="3 3" /><Area dataKey="price" name="Price USD" stroke="#b6ff4a" fill="url(#oracle-price)" dot={(props: { cx?: number; cy?: number; payload?: OracleRound }) => props.payload?.status !== "normal" ? <circle cx={props.cx} cy={props.cy} r={3} fill={props.payload?.status === "stale" ? "#e6a940" : "#ee5b4f"} /> : <g />} /><Line dataKey="rollingMean" name="Rolling mean" stroke="#d7d2c2" dot={false} strokeWidth={1} /></AreaChart></ResponsiveContainer> : <DataUnavailable />}</div><SourceFooter source="Chainlink TUSD/USD supplied sample" type="HISTORICAL" updated="10 Nov 2022" /></Panel>;
  if (tab === "DEVIATION") view = <Panel><PanelHeader title="Rolling statistical deviation" meta="WINDOW = 5 ROUNDS" action={<ProvenanceBadge type="DERIVED" />} /><div className="h-[390px] p-3"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData}><CartesianGrid stroke="#202420" vertical={false} /><XAxis dataKey="label" stroke="#555b55" fontSize={8} tickLine={false} axisLine={false} minTickGap={45} /><YAxis domain={[-2.5,2.5]} stroke="#555b55" fontSize={8} tickLine={false} axisLine={false} /><Tooltip content={<TerminalTooltip />} /><ReferenceLine y={1.5} stroke="#e6a940" strokeDasharray="4 4" /><ReferenceLine y={-1.5} stroke="#e6a940" strokeDasharray="4 4" /><ReferenceLine y={0} stroke="#555b55" /><Line dataKey="zScore" name="Z-score" stroke="#e6a940" dot={(props: { cx?: number; cy?: number; payload?: OracleRound }) => Math.abs(props.payload?.zScore ?? 0) >= 1.5 ? <circle cx={props.cx} cy={props.cy} r={3} fill="#ee5b4f" /> : <g />} /></LineChart></ResponsiveContainer></div><SourceFooter source="Safe Sphere rolling calculation" type="DERIVED" /></Panel>;
  if (tab === "FRESHNESS") view = <Panel><PanelHeader title="Round update intervals" meta="HOURS" action={<ProvenanceBadge type="DERIVED" />} /><div className="h-[390px] p-3"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><CartesianGrid stroke="#202420" vertical={false} /><XAxis dataKey="label" stroke="#555b55" fontSize={8} tickLine={false} axisLine={false} minTickGap={45} /><YAxis stroke="#555b55" fontSize={8} tickLine={false} axisLine={false} /><Tooltip content={<TerminalTooltip />} /><ReferenceLine y={6} stroke="#ee5b4f" strokeDasharray="4 4" label={{ value: "6H THRESHOLD", fill: "#ee5b4f", fontSize: 8 }} /><Area dataKey="intervalHours" name="Interval hours" stroke="#d5c28b" fill="#d5c28b18" /></AreaChart></ResponsiveContainer></div><SourceFooter source="Safe Sphere timestamp delta" type="DERIVED" /></Panel>;
  if (tab === "ANOMALIES") view = <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{anomalies.map((round) => <Panel key={round.roundId}><PanelHeader title={`Round ${round.aggregatorRoundId}`} action={<StatusBadge status={round.status === "stale" ? "warning" : "notice"} label={round.status} />} /><div className="p-4"><div className="font-mono text-xl">${round.price.toFixed(8)}</div><div className="mt-4 grid grid-cols-2 gap-3 font-mono text-[10px]"><div><div className="eyebrow">Z-score</div><div className="mt-1">{round.zScore?.toFixed(3) ?? "—"}σ</div></div><div><div className="eyebrow">Interval</div><div className="mt-1">{round.interval ? `${(round.interval / 3600).toFixed(2)}h` : "—"}</div></div></div><div className="mt-4 border-t border-line pt-3 font-mono text-[9px] text-muted">{round.dateTime}</div></div><SourceFooter source="Chainlink sample + Safe Sphere" type="DERIVED" /></Panel>)}</div>;
  if (tab === "RAW ROUNDS") view = <Panel><PanelHeader title="Raw oracle rounds" meta={`${rounds.length} ROWS`} /><div className="overflow-x-auto"><table className="data-table min-w-[1200px]"><thead><tr><th>Round ID</th><th>Price</th><th>Updated at</th><th>Interval</th><th>Change</th><th>Rolling mean</th><th>Rolling std</th><th>Z-score</th><th>Status</th></tr></thead><tbody>{rounds.map((round) => <tr key={round.roundId}><td>{round.roundId}</td><td>${round.price.toFixed(8)}</td><td>{round.dateTime}</td><td>{round.interval ? `${round.interval.toLocaleString()} sec` : "—"}</td><td>{round.change === null ? "—" : `${round.change.toFixed(4)}%`}</td><td>{round.rollingMean?.toFixed(8) ?? "—"}</td><td>{round.rollingStd?.toFixed(8) ?? "—"}</td><td>{round.zScore?.toFixed(3) ?? "—"}</td><td><StatusBadge status={round.status === "stale" ? "warning" : round.status === "deviation" ? "notice" : "healthy"} label={round.status} /></td></tr>)}</tbody></table></div><SourceFooter source="Chainlink sample; derived columns by Safe Sphere" type="DERIVED" /></Panel>;

  return <PageFrame eyebrow="Oracle research / 08" title="Oracle Intelligence Lab" description="Historical TUSD/USD rounds with transparent rolling statistics. Thresholds are analytical controls, not proof of manipulation." type="HISTORICAL" actions={<Button size="sm" onClick={exportRows}><Download className="h-3 w-3" />Export analysis</Button>}>
    <div className="grid grid-cols-2 gap-px bg-line lg:grid-cols-6"><Metric label="Latest sample price" value={latest ? `$${latest.price.toFixed(8)}` : "—"} type="HISTORICAL" /><Metric label="Sample average" value={average ? `$${average.toFixed(8)}` : "—"} type="DERIVED" /><Metric label="Max abs Z-score" value={maxZ ? `${maxZ.toFixed(3)}σ` : "—"} type="DERIVED" /><Metric label="Anomaly points" value={anomalies.length} type="DERIVED" tone={anomalies.length ? "amber" : "green"} /><Metric label="Sample rounds" value={rounds.length || "—"} type="HISTORICAL" /><Metric label="Date range" value="08–10 NOV" detail="2022 / UTC" type="HISTORICAL" /></div>
    <div className="mt-3 flex overflow-x-auto border-b border-line">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={cn("h-10 border-b px-4 font-mono text-[9px] font-semibold", tab === item ? "border-signal text-bone" : "border-transparent text-muted")}>{item}</button>)}</div><div className="mt-3">{view}</div>
  </PageFrame>;
}
