"use client";

import { Check, Copy, ExternalLink, KeyRound, RefreshCw } from "lucide-react";
import { PageFrame, RefreshButton } from "@/components/page-frame";
import { useApi } from "@/hooks/use-api";
import { Button, Panel, PanelHeader, ProvenanceBadge, SourceFooter, StatusBadge } from "@/components/ui/primitives";

interface SourceRecord { id: string; name: string; status: string; detail: string; required: boolean }
interface StatusResponse { data: SourceRecord[]; checkedAt: string }

export function SettingsPage() {
  const result = useApi<StatusResponse>("/api/status");
  return <PageFrame eyebrow="System control / 16" title="API & Source Status" description="Runtime source health and configuration readiness. Secret values are read server-side and never returned to the interface." type="DERIVED" actions={<RefreshButton onClick={result.refresh} loading={result.loading} />}>
    <div className="grid gap-3 lg:grid-cols-[1fr_340px]">
      <Panel><PanelHeader title="Source registry" meta={`${result.data?.data.length ?? 0} CONNECTORS`} /><div className="divide-y divide-line">{result.data?.data.map((source) => { const online = ["operational", "configured", "public", "public-fallback", "local-module", "local-only"].includes(source.status); return <div key={source.id} className="grid gap-3 px-4 py-4 md:grid-cols-[1fr_140px_1.2fr]"><div className="flex items-center gap-3"><span className={`h-2 w-2 rounded-full ${online ? "bg-signal" : "bg-[#5b615b]"}`} /><div><div className="text-[12px] font-semibold">{source.name}</div><div className="mt-1 font-mono text-[8px] uppercase text-muted">{source.required ? "Credential-backed" : "No key required"}</div></div></div><div><StatusBadge status={online ? "healthy" : "notice"} label={source.status} /></div><div className="font-mono text-[9px] leading-5 text-muted">{source.detail}</div></div>})}</div><SourceFooter source="Server runtime + local filesystem" type="DERIVED" updated={result.data?.checkedAt} /></Panel>
      <div className="space-y-3"><Panel><PanelHeader title="Configuration" meta="ENVIRONMENT" /><div className="p-4"><div className="flex h-10 items-center border border-line bg-[#090b0a] px-3 font-mono text-[9px] text-muted"><KeyRound className="mr-2 h-3.5 w-3.5" />.env.local <span className="ml-auto">SERVER ONLY</span></div><p className="mt-4 text-[10px] leading-5 text-muted">Copy variable names from <code className="text-bone">.env.example</code>. Missing credentials leave related live panels blank without affecting historical mode.</p><div className="mt-4 space-y-2 font-mono text-[9px]">{["ALCHEMY_RPC_URL", "ETHERSCAN_API_KEY", "TENDERLY_ACCESS_KEY", "NEXT_PUBLIC_SUPABASE_URL"].map((name) => <div key={name} className="flex items-center border-b border-line pb-2"><span>{name}</span><span className="ml-auto text-muted">OPTIONAL</span></div>)}</div></div></Panel><Panel><PanelHeader title="Deployment readiness" /><div className="space-y-3 p-4 font-mono text-[9px]"><div className="flex"><Check className="mr-2 h-3 w-3 text-signal" />Next.js / Vercel</div><div className="flex"><Check className="mr-2 h-3 w-3 text-signal" />FastAPI / Railway or Render</div><div className="flex"><Check className="mr-2 h-3 w-3 text-signal" />PostgreSQL schema included</div><div className="flex"><Check className="mr-2 h-3 w-3 text-signal" />Tenderly credential interface</div></div></Panel></div>
    </div>
    <Panel className="mt-3"><PanelHeader title="Integrity policy" action={<ProvenanceBadge type="DERIVED" />} /><div className="grid gap-px bg-line md:grid-cols-3"><div className="bg-panel p-4"><div className="eyebrow">Unavailable sources</div><p className="mt-3 text-[11px] leading-5 text-muted">The UI shows an explicit unavailable state. Historical data is never relabeled as live.</p></div><div className="bg-panel p-4"><div className="eyebrow">Missing metrics</div><p className="mt-3 text-[11px] leading-5 text-muted">Unknown values display an em dash. No financial or chain value is synthesized.</p></div><div className="bg-panel p-4"><div className="eyebrow">Security language</div><p className="mt-3 text-[11px] leading-5 text-muted">Signals request investigation and describe potential exposure; they do not predict certain compromise.</p></div></div></Panel>
  </PageFrame>;
}
